---
- name: Run packit-service tests
  hosts: all
  tasks:
  - include_tasks: tasks/zuul-project-setup.yaml
  - name: Run tests within a container
    command: "make check_in_container"
    args:
      chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    become: true
  - name: Copy secrets to packit-service dir
    copy:
      src: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/packit-service/deployment'].src_dir }}/secrets"
      dest: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/secrets"
  - name: Run tests which are executed within openshift
    command: make check-inside-openshift
    args:
      chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    become: true
